import type { CSSProperties } from 'react';
import { colors, spacing, typography, radii, shadows } from '../Global';

export const createEventStyles: Record<string, CSSProperties> = {
  page: {
    display: 'flex',
    flexDirection: 'column',
    minHeight: '100vh',
    backgroundColor: colors.background,
  },
  main: {
    flex: 1,
    width: '100%',
    maxWidth: '48rem',
    margin: '0 auto',
    padding: spacing.xl,
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.xl,
  },
  headerSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.xs,
  },
  heading: {
    fontSize: typography.sizes.xl,
    fontWeight: typography.weights.semibold,
    color: colors.textPrimary,
    fontFamily: typography.fontFamily,
  },
  subheading: {
    fontSize: typography.sizes.sm,
    color: colors.textSecondary,
    fontFamily: typography.fontFamily,
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.lg,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: radii.md,
    padding: spacing.xl,
    boxShadow: shadows.md,
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.lg,
  },
  cardTitle: {
    fontSize: typography.sizes.md,
    fontWeight: typography.weights.semibold,
    color: colors.textPrimary,
    fontFamily: typography.fontFamily,
    margin: 0,
  },
  fieldGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.sm,
  },
  label: {
    fontSize: typography.sizes.sm,
    fontWeight: typography.weights.medium,
    color: colors.textPrimary,
    fontFamily: typography.fontFamily,
  },
  input: {
    width: '100%',
    padding: `${spacing.sm} ${spacing.md}`,
    border: `1px solid ${colors.border}`,
    borderRadius: radii.sm,
    fontSize: typography.sizes.base,
    fontFamily: typography.fontFamily,
    color: colors.textPrimary,
    backgroundColor: colors.white,
    outline: 'none',
    boxSizing: 'border-box',
  },
  textarea: {
    width: '100%',
    padding: `${spacing.sm} ${spacing.md}`,
    border: `1px solid ${colors.border}`,
    borderRadius: radii.sm,
    fontSize: typography.sizes.base,
    fontFamily: typography.fontFamily,
    color: colors.textPrimary,
    backgroundColor: colors.white,
    outline: 'none',
    resize: 'vertical',
    minHeight: '6rem',
    boxSizing: 'border-box',
  },
  select: {
    width: '100%',
    padding: `${spacing.sm} ${spacing.md}`,
    border: `1px solid ${colors.border}`,
    borderRadius: radii.sm,
    fontSize: typography.sizes.base,
    fontFamily: typography.fontFamily,
    color: colors.textPrimary,
    backgroundColor: colors.white,
    outline: 'none',
    cursor: 'pointer',
    boxSizing: 'border-box',
  },
  row: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: spacing.lg,
  },
  actions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: spacing.md,
    paddingTop: spacing.sm,
  },
  buttonPrimary: {
    padding: `${spacing.sm} ${spacing.xl}`,
    backgroundColor: colors.primary,
    color: colors.white,
    border: 'none',
    borderRadius: radii.sm,
    fontSize: typography.sizes.base,
    fontWeight: typography.weights.medium,
    fontFamily: typography.fontFamily,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: spacing.sm,
    transition: 'background-color 0.2s',
  },
  buttonSecondary: {
    padding: `${spacing.sm} ${spacing.xl}`,
    backgroundColor: 'transparent',
    color: colors.textSecondary,
    border: `1px solid ${colors.border}`,
    borderRadius: radii.sm,
    fontSize: typography.sizes.base,
    fontWeight: typography.weights.medium,
    fontFamily: typography.fontFamily,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: spacing.sm,
    transition: 'background-color 0.2s',
  },
  errorText: {
    fontSize: typography.sizes.xs,
    color: colors.danger,
    fontFamily: typography.fontFamily,
  },
};
