import type { CSSProperties } from 'react';
import { colors, spacing, typography, radii, shadows } from '../Global';

export const proveedoresListStyles: Record<string, CSSProperties> = {
  page: {
    display: 'flex',
    flexDirection: 'column',
    minHeight: '100vh',
    backgroundColor: colors.background,
  },
  main: {
    flex: 1,
    width: '100%',
    maxWidth: '72rem',
    margin: '0 auto',
    padding: spacing.xl,
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.xl,
  },
  headerSection: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  headerText: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.xs,
  },
  heading: {
    fontSize: typography.sizes.xl,
    fontWeight: typography.weights.semibold,
    color: colors.textPrimary,
    fontFamily: typography.fontFamily,
  },
  subheading: {
    fontSize: typography.sizes.sm,
    color: colors.textSecondary,
    fontFamily: typography.fontFamily,
  },
  createButton: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing.sm,
    padding: `${spacing.sm} ${spacing.lg}`,
    backgroundColor: colors.primary,
    color: colors.white,
    border: 'none',
    borderRadius: radii.sm,
    fontSize: typography.sizes.base,
    fontWeight: typography.weights.medium,
    fontFamily: typography.fontFamily,
    cursor: 'pointer',
    textDecoration: 'none',
    transition: 'background-color 0.2s',
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: radii.md,
    boxShadow: shadows.md,
    overflow: 'hidden',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
  },
  th: {
    textAlign: 'left',
    padding: `${spacing.md} ${spacing.lg}`,
    fontSize: typography.sizes.sm,
    fontWeight: typography.weights.semibold,
    color: colors.textSecondary,
    fontFamily: typography.fontFamily,
    borderBottom: `1px solid ${colors.border}`,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
  },
  td: {
    padding: `${spacing.md} ${spacing.lg}`,
    fontSize: typography.sizes.base,
    color: colors.textPrimary,
    fontFamily: typography.fontFamily,
    borderBottom: `1px solid ${colors.border}`,
  },
  badge: {
    display: 'inline-block',
    padding: `${spacing.xs} ${spacing.sm}`,
    borderRadius: radii.sm,
    fontSize: typography.sizes.xs,
    fontWeight: typography.weights.medium,
    fontFamily: typography.fontFamily,
  },
  actionButton: {
    padding: `${spacing.xs} ${spacing.sm}`,
    border: 'none',
    borderRadius: radii.sm,
    cursor: 'pointer',
    fontSize: typography.sizes.sm,
    fontFamily: typography.fontFamily,
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacing.xs,
    marginRight: spacing.xs,
  },
  emptyState: {
    padding: spacing.xxl,
    textAlign: 'center',
    color: colors.textSecondary,
    fontFamily: typography.fontFamily,
    fontSize: typography.sizes.base,
  },
  loadingState: {
    padding: spacing.xxl,
    textAlign: 'center',
    color: colors.textSecondary,
    fontFamily: typography.fontFamily,
    fontSize: typography.sizes.base,
  },
};
